{% set name = "craftr" %}
{% set version = "2.0.0.dev7" %}
{% set sha256 = "b7e4b7c78f3adb0c78c8bdb8cb82e7118dad2246491fd2c892cf24f42c26d519" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/craftr-build/{{ name }}/archive/old-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - cson ==0.7
    - colorama ==0.3.7
    - glob2 ==0.5
    - jsonschema ==2.5.1
    - ninja
    - ninja_syntax ==1.6.0
    - nr ==1.3.5
    - termcolor ==1.1.0
    - werkzeug ==0.11.11

test:
  commands:
    - craftr -h

about:
  home: https://craftr.net
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Meta build system based on Ninja and Python'
  description: |
    Craftr is a next generation build system based on Ninja and Python that
    features modular and cross-platform build definitions at the flexibility of a
    Python script and provides access to multiple levels of build automation
    abstraction.
  doc_url: http://craftr.readthedocs.io
  dev_url: https://github.com/craftr-build/craftr

extra:
  recipe-maintainers:
    - dfroger
